//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TwitchBot.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.5.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SettingsProxyTXT {
            get {
                return ((string)(this["SettingsProxyTXT"]));
            }
            set {
                this["SettingsProxyTXT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SettingsProxyCHK {
            get {
                return ((bool)(this["SettingsProxyCHK"]));
            }
            set {
                this["SettingsProxyCHK"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SettingsOnStartSteamCHK {
            get {
                return ((bool)(this["SettingsOnStartSteamCHK"]));
            }
            set {
                this["SettingsOnStartSteamCHK"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SettingsAutoLinkingDisableCHK {
            get {
                return ((bool)(this["SettingsAutoLinkingDisableCHK"]));
            }
            set {
                this["SettingsAutoLinkingDisableCHK"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SettingsAutoDetectingDisableCHK {
            get {
                return ((bool)(this["SettingsAutoDetectingDisableCHK"]));
            }
            set {
                this["SettingsAutoDetectingDisableCHK"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4000")]
        public int SettingsReactionDelayFromTXT {
            get {
                return ((int)(this["SettingsReactionDelayFromTXT"]));
            }
            set {
                this["SettingsReactionDelayFromTXT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5000")]
        public int SettingsReactionDelayToTXT {
            get {
                return ((int)(this["SettingsReactionDelayToTXT"]));
            }
            set {
                this["SettingsReactionDelayToTXT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4000")]
        public int SettingsMessagesDelayFromTXT {
            get {
                return ((int)(this["SettingsMessagesDelayFromTXT"]));
            }
            set {
                this["SettingsMessagesDelayFromTXT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5000")]
        public int SettingsMessagesDelayToTXT {
            get {
                return ((int)(this["SettingsMessagesDelayToTXT"]));
            }
            set {
                this["SettingsMessagesDelayToTXT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("isybycnsmam")]
        public string FormChannelNameTXT {
            get {
                return ((string)(this["FormChannelNameTXT"]));
            }
            set {
                this["FormChannelNameTXT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("6000")]
        public int FormFollowDelayFromTXT {
            get {
                return ((int)(this["FormFollowDelayFromTXT"]));
            }
            set {
                this["FormFollowDelayFromTXT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("8000")]
        public int FormFollowDelayToTXT {
            get {
                return ((int)(this["FormFollowDelayToTXT"]));
            }
            set {
                this["FormFollowDelayToTXT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("!giveaway@#@!giveaway2@#@LUL")]
        public string FormMessageClipboardTXT {
            get {
                return ((string)(this["FormMessageClipboardTXT"]));
            }
            set {
                this["FormMessageClipboardTXT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3000")]
        public int FormMessageDelayFromTXT {
            get {
                return ((int)(this["FormMessageDelayFromTXT"]));
            }
            set {
                this["FormMessageDelayFromTXT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5000")]
        public int FormMessageDelayToTXT {
            get {
                return ((int)(this["FormMessageDelayToTXT"]));
            }
            set {
                this["FormMessageDelayToTXT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("isybycnsmam")]
        public string FormSearchBoxTXT {
            get {
                return ((string)(this["FormSearchBoxTXT"]));
            }
            set {
                this["FormSearchBoxTXT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int FormLastSteamAccSelected {
            get {
                return ((int)(this["FormLastSteamAccSelected"]));
            }
            set {
                this["FormLastSteamAccSelected"] = value;
            }
        }
    }
}
